### ISSUE TITLE
TypeError: expected str, bytes or os.PathLike object, not list

### ISSUE THREAD

**Issue by CallOn84** [CSSLab/maia-chess#55]
Hi.

While trying to start train_maia.py, it gave me this error:

```
Traceback (most recent call last):
  File "\move_prediction\train_maia.py", line 187, in <module>
    main(args.config, name, collection_name)
  File "\move_prediction\train_maia.py", line 29, in main
    train_chunks = get_latest_chunks(cfg['dataset']['input_train'])
  File "\move_prediction\train_maia.py", line 98, in get_latest_chunks
    maia_chess_backend.printWithDate(f"found {glob.glob(path)} chunk dirs")
  File "C:\Program Files\Python39\lib\glob.py", line 22, in glob
    return list(iglob(pathname, recursive=recursive))
  File "C:\Program Files\Python39\lib\glob.py", line 43, in _iglob
    dirname, basename = os.path.split(pathname)
  File "C:\Program Files\Python39\lib\ntpath.py", line 185, in split
    p = os.fspath(p)
TypeError: expected str, bytes or os.PathLike object, not list
```

For context, here is my config file:

```
%YAML 1.2
---
gpu: 0

dataset:
  num_chunks: 100000000
  allow_less_chunks: true
  train_ratio: 0.70
  input_train:
    - '\move_prediction\trainingdata\supervised-0\'
    - '\move_prediction\trainingdata\supervised-1\'
    - '\move_prediction\trainingdata\supervised-2\'
  input_test:
    - '\move_prediction\trainingdata\supervised-0\'
    - '\move_prediction\trainingdata\supervised-1\'
    - '\move_prediction\trainingdata\supervised-2\'
  train_workers: 32
  test_workers: 8

training:
    swa: true
    swa_output: true
    swa_steps: 100
    swa_max_n: 10
    mask_legal_moves: true
    lookahead_optimizer: true
    precision: 'half'
    batch_size: 1024
    num_batch_splits: 1
    test_steps: 2000
    num_test_positions: 131072
    train_avg_report_steps: 50
    total_steps: 400000
    checkpoint_steps: 10000
    shuffle_size: 250000
    lr_values:
        - 0.1
        - 0.01
        - 0.001
        - 0.0001
    lr_boundaries:
        - 80000
        - 200000
        - 360000
    policy_loss_weight: 1.0            # weight of policy loss
    value_loss_weight: 1.0             # weight of value loss
    moves_left_loss_weight: 0.1
    moves_left_gradient_flow: 1.0

model:
  filters: 64
  residual_blocks: 6
  se_ratio: 8
...
```

I don't understand why it's giving me this `TypeError: expected str, bytes or os.PathLike object, not list` error. Any help would be appreciated.

**Comment by reidmcy** [comment]
Your providing a list in the yaml, it's expecting a string

**Comment by CallOn84** [comment]
> Your providing a list in the yaml, it's expecting a string

The yaml for maia_config is in a list, so I don't get it.

**Comment by CallOn84** [comment]
> Please check again, [here](https://github.com/CSSLab/maia-chess/blob/master/move_prediction/maia_config.yaml#L6) this is the relevant line. I'm not sure which config you are using there

Ah, thanks. It works now. However, when it goes through the training games, it comes back as 0 chunks total. I don't know why that happening when there's the data there.

**Comment by reidmcy** [comment]
It's not looking for the the directory to the files, did you read the comment in the yaml?

**Comment by CallOn84** [comment]
> It's not looking for the the directory to the files, did you read the comment in the yaml?

This is the YAML I have. I followed the YAML in the repository, so I don't know what's wrong.

```
%YAML 1.2
---
gpu: 0

dataset:
  allow_less_chunks: true
  input_train: 'PATH_TO\move_prediction\trainingdata\*\*'
  input_test: 'PATH_TO\move_prediction\trainingdata\*\*'

training:
    precision: 'half'
    batch_size: 1024
    num_batch_splits: 1
    test_steps: 2000
    num_test_positions: 131072
    train_avg_report_steps: 50
    total_steps: 400000
    checkpoint_steps: 10000
    shuffle_size: 250000
    lr_values:
        - 0.1
        - 0.01
        - 0.001
        - 0.0001
    lr_boundaries:
        - 80000
        - 200000
        - 360000
    policy_loss_weight: 1.0            # weight of policy loss
    value_loss_weight: 1.0             # weight of value loss
    moves_left_loss_weight: 0.1
    moves_left_gradient_flow: 1.0

model:
  filters: 64
  residual_blocks: 6
  se_ratio: 8
...
```
